name: ashuothshh job 
# trigger point 
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

# creating jobs 
jobs:
  infra-provision-job:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    # calling first github action to clone my dryrun-aws data to runner machine 
    - name: taking code from my repo 
      uses: actions/checkout@v5
      with:
        ref: master 
# terrafor installing 
    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3
# running some commands 
    - name: my first step to test github action 
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
        terraform version
    # configure aws secret keys 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: verify aws connection 
      run: | 
        echo "checking with command"
        aws s3 ls 
    - name: deploy terraform resources 
      run: | 
        echo "implementing terraform deals"
        terraform init 
        terraform plan 
        sleep 2
        terraform apply --auto-approve 
        ls modules/ec2
# creating artifact and uploading ansible inventory file 
    - name: uploading ansible inventory to github artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ashutoshh-github-artifact
        path: |
          modules/ec2/ansible-inventory.txt
          modules/ec2/ashutoshh-key.pem

  infra-configure-job:
    needs: infra-provision-job
    runs-on: ubuntu-latest
    steps:
    - name: checking out code 
      uses: actions/checkout@v5
      with:
        ref: master 
        sparse-checkout: |
          my-ansible
    - name: verify checkout 
      run: | 
        ls -R 
# downloading artifact the one i created above
    - name: downloading ansible inventory from artifact 
      uses: actions/download-artifact@v5
      with:
        name: ashutoshh-github-artifact
# listing artifact
    - name: Display structure of downloaded files
      run: ls -R

    # isntalling  ansible  
    - name: installing ansible  
      run: | 
        echo "setup of ansible in ubuntu machine"
        sudo apt update
        sudo apt install ansible -y 
        ansible --version 

    - name: running ansible playbook in dynamic inventory 
      run: | 
        echo "Running ansible playbook"
        chmod 400 ashutoshh-key.pem
        cd my-ansible
        ansible-playbook -i ../ansible-inventory.txt --private-key ../ashutoshh-key.pem playbook1.yaml

    


          

  